[skip ci] Try to use schema-profunctor lib.
wireapp/wire-server pull request #1512
Opened 2021-05-18 07:10 UTC by fisx

2021-05-18 09:57 UTC, pcapriotti requested changes
I have left some comments.

If it's not too much of a pain, could you also make the `Schema` import unqualified, and qualify `Aeson`? This is the way I've dealt with imports in other places.

2021-05-18 09:57 UTC, pcapriotti commented on libs/wire-api/src/Wire/API/User/Client.hs
> +
You should use `enum` here. Something like:
```haskell
S.enum @Text "SupportedClientFeature" $
  S.element "legalhold-implicit-consent" ClientSupportsLegalholdImplicitConsent
```

2021-05-18 09:57 UTC, pcapriotti commented on libs/wire-api/src/Wire/API/User/Client.hs
> +
These can be derived automatically if you write an `S.ToSchema` instance. Something like the following should work (haven't tried compiling it though):
```haskell
S.object "SupportedClientFeatureList" $
  fromSupportedClientFeatureList S..= S.field "feature_list" S.schema
```

2021-05-19 05:12 UTC, fisx commented
thanks, this is helpful!  I tried again, and got stuck a little further down, but i think i'm almost there.  :)

as for the unqualified import of `Data.Schema`, I would like to leave that for a dedicated refactoring PR that transforms the entire module, otherwise it'll get too noisy.

NB: we've tried to establish a policy in the backend chapter that forbids unqualified, implicit imports.  with limited success, admittedly, but there appeared to be a weak consensus when we debated it.

2021-05-19 06:24 UTC, pcapriotti approved these changes
Looks good! Agreed about the unqualified import, that can be done separately.

You can also attach descriptions using `objectWithDocModifier "name" (description ?~ "desc")` instead of `object "name"`.

Minor nitpick follows.

2021-05-19 06:24 UTC, pcapriotti commented on libs/wire-api/src/Wire/API/User/Client.hs
> +        <$> (fromSupportedClientFeatureList Schema..= Schema.field "feature_list" Schema.schema)
The brackets here should not be necessary.

2021-05-19 08:14 UTC, fisx commented
looks good, but doesn't compile yet!  :)  can you guess the type error from looking at the change?

2021-05-19 08:16 UTC, fisx commented
spoiler:

```
/home/mf/src/wire/wire-server/libs/wire-api/src/Wire/API/User/Client.hs:182:12: error:
    • Couldn't match type ‘[SupportedClientFeature]’
                     with ‘Set SupportedClientFeature’
```

2021-05-19 09:40 UTC, pcapriotti commented
Ah, sorry, I didn't realise there was a type mismatch there. You can fix it by adding the set to list conversion functions in the right place. Here's an excerpt from the schema for `NewConv`:
```haskell
      <*> (Set.toList . newConvAccess)
        .= ( field "access" (Set.fromList <$> array schema)
               <|> pure mempty
           )
```

2021-05-19 13:03 UTC, merged