Legalhold: dynamic whitelisted teams [skip ci]
wireapp/wire-server pull request #1557
Opened 2021-05-31 17:31 UTC by smatting

2021-05-31 21:34 UTC, fisx approved these changes
I've deactivated the test suite so you can deploy this on staging to make some progress with QA and the team.

Ideas for getting the test suite back on track:

- Don't use `deleteLHWhitelistTeam`, but `deleteTeam`.  The latter is implicit in `withTeam`.  (See my commits and the comments that come with them.)
- Don't remove `grantConsent*`, but check the galley server config.  If LH is `disabled-by-default`, use `grantConsent*` (those tests did work until before this PR); if it is `whitelist-implicit-consent`, use `putLHWhitelistTeam`.  Remember to use `withTeam` if you do that.
- Where the behavior differs, branch on feature flag again.  Again, the old behavior should work already, the new may need adjusting.

I am still hoping all of the necessary changes will be quite local, but I can't see that very clearly yet.

2021-06-01 08:25 UTC, smatting commented on hack/helm_vars/wire-server/values.yaml
> +        legalhold: disabled-by-default
this is not the default. this is for ci

2021-06-01 08:39 UTC, smatting commented on services/galley/src/Galley/App.hs
> +createEnv :: (ClientState -> Opts -> IO (Maybe [TeamId])) -> Metrics -> Opts -> IO Env
I don't think this works. The environment isn't created on every request, but only in `mkApp`, which itself is also called once in Galley.run.run

2021-06-01 19:17 UTC, fisx commented
I sometimes get the tests to pass now locally, sometimes this happens:

```
     handshake between LH device and user with old clients is blocked:                                   FAIL                                                                                                                                                         
        Exception: HttpExceptionRequest Request {                                                                                                                                                                                                                      
          host                 = "127.0.0.1"                                                                                                                                                           
          port                 = 8085                                                                                                                                                                  
          secure               = False                                                                                                                                                                                                                                 
          requestHeaders       = [("Content-Type","application/json")]                                                                                                                                 
          path                 = "i/teams/54dcbff8-73ba-496e-9740-b523c24f9268/features/legalhold"                                                                                                     
          queryString          = ""                                                                                                                                                                                                                                    
          method               = "PUT"                                                                                                                                                                                                                                           proxy                = Nothing                                                                                                                                                                                                                               
          rawBody              = False                                                                                                                                                                                                                                 
          redirectCount        = 10                                                                                                                                                                    
          responseTimeout      = ResponseTimeoutDefault                                                                                                                                                
          requestVersion       = HTTP/1.1                                                                                                                                                 
        }                                                                                                                                                                                                                                                              
         (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Tue, 01 Jun 2021 18:54:31 GMT"),("Server","Warp/3.3.13"),("Co
ntent-Type","application/json")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "{\"code\":403,\"message\":\"legal hold is enabled for teams via server config and cannot be changed here\",\"label\":\"legalhold-whitelist
ed-only\"}")                                                                                                                                              
      User cannot fetch prekeys of LH users if consent is missing:                                        [brig] W, logger=cassandra.brig, Server warning: Read 0 live rows and 1347 tombstone cells for query SELECT * FROM brig_test.users_pending_activation WHERE  
LIMIT 10000 (see tombstone_warn_threshold)                                                                                                                                                                                                                             
FAIL                                                                                                                                                                                                                                                                   
        Exception: HttpExceptionRequest Request {                                                                                                                                                      
          host                 = "127.0.0.1"                                                                                                                                                           
          port                 = 8085                                                                                                                                                     
          secure               = False                                                                                                                                                                                                                                 
          requestHeaders       = [("Content-Type","application/json")]                                                                                                                                 
          path                 = "i/teams/6974b45f-6e86-4a90-992d-9d4aad5e5e3e/features/legalhold"                                                                                                     
          queryString          = ""                                                                                                                                                                                                                                    
          method               = "PUT"
          proxy                = Nothing
          rawBody              = False
          redirectCount        = 10
          responseTimeout      = ResponseTimeoutDefault
          requestVersion       = HTTP/1.1
        }
         (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Tue, 01 Jun 2021 18:54:32 GMT"),("Server","Warp/3.3.13"),("Co
ntent-Type","application/json")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "{\"code\":403,\"message\":\"legal hold is enabled for teams via server config and cannot be changed here\",\"label\":\"legalhold-whitelist
ed-only\"}")
      User cannot fetch prekeys of LH users: if user has old client:                                      FAIL
        Exception: HttpExceptionRequest Request {
          host                 = "127.0.0.1"
          port                 = 8085
          secure               = False
          requestHeaders       = [("Content-Type","application/json")]
          path                 = "i/teams/63b26d54-fb75-4045-aeed-4197faf80711/features/legalhold"
          queryString          = ""
          method               = "PUT"
          proxy                = Nothing
          rawBody              = False
          redirectCount   [...]

2021-06-02 13:25 UTC, jschaul requested changes

2021-06-02 13:25 UTC, jschaul commented on charts/nginz/values.yaml
> +    - path /i/legalhold/whitelisted-teams(.*)
```suggestion
    - path: /i/legalhold/whitelisted-teams(.*)
```

Also, you need regex support, see `~*` from above queries.

2021-06-02 13:38 UTC, merged