RPC for sending messages to remove conversations
wireapp/wire-server pull request #1609
Opened 2021-06-21 14:38 UTC by pcapriotti

## Checklist

 - [x] Title of this PR explains the impact of the change.
 - [ ] The description provides context as to why the change should occur and
       what the code contributes to that effect. This could also be a link to a
       JIRA ticket or a Github issue, if there is one.
 - [ ] The CHANGELOG.md file in the *Unreleased* section has been updated to
       explain the change which will be included in the release notes.
 - [ ] If a component uses a new or changed internal endpoint of another
       component, this is mentioned in the CHANGELOG.md.
- [ ] If this PR creates a new endpoint, or adds a new configuration flag, the endpoint / config-flag checklist (see Wire-employee only backend [wiki page](https://github.com/zinfra/backend-wiki/wiki/Checklists)) has been followed.

2021-07-06 14:53 UTC, smatting requested changes

2021-07-06 14:55 UTC, smatting commented on libs/wire-api-federation/src/Wire/API/Federation/Util/Aeson.hs
> +instance All UnionMember as => ToJSON (CustomEncodedUnion as) where
This has it's own PR now https://github.com/wireapp/wire-server/pull/1639

2021-07-06 15:10 UTC, akshaymankar commented on services/galley/src/Galley/API/Message.hs
> +          (senderDomain, senderUser, qualifiedNewOtrSender msg)
```suggestion
          (senderDomain, senderUser, senderClient)
```

2021-07-06 15:36 UTC, akshaymankar approved these changes
Looks good now, will wait for others to review.

2021-07-06 15:36 UTC, smatting approved these changes

2021-07-06 16:55 UTC, jschaul approved these changes
Except that CI doesn't seem happy yet, the code here looks good!

2021-07-07 07:06 UTC, akshaymankar commented
> Except that CI doesn't seem happy yet, the code here looks good!

Rebase broke it, fixed in d1149c857bdb3dc2b039f70e45d074b68b2a0f67

2021-07-07 07:43 UTC, pcapriotti commented
Looks good to me. I guess we can actually remove `UnionT` altogether, since it's dead code now.

2021-07-07 08:18 UTC, akshaymankar commented
> Looks good to me. I guess we can actually remove `UnionT` altogether, since it's dead code now.

Created https://github.com/wireapp/wire-server/pull/1647

2021-07-07 09:21 UTC, merged