Update LH api docs.
wireapp/wire-server pull request #1627
Opened 2021-06-24 13:06 UTC by fisx

## Checklist

 - [ ] Title of this PR explains the impact of the change.
 - [ ] The description provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [ ] The CHANGELOG.md file in the *Unreleased* section has been updated to explain the change which will be included in the release notes.
 - [ ] If a component uses a new or changed internal endpoint of another component, this is mentioned in the CHANGELOG.md.
- [ ] If this PR creates a new endpoint, or adds a new configuration flag, the endpoint / config-flag checklist (see Wire-employee only backend [wiki page](https://github.com/zinfra/backend-wiki/wiki/Checklists)) has been followed.

2021-06-28 14:01 UTC, fisx commented
(@franziskuskiefer you probably want to just check out https://github.com/wireapp/wire-server/blob/lh-docs/docs/reference/team/legalhold.md; @smatting requesting your review to get this merged soon, please just take a quick glance if there are any wild inaccurracies.)

2021-06-30 17:03 UTC, smatting requested changes

2021-06-30 17:03 UTC, smatting commented on docs/reference/team/legalhold.md
> +Otherwise, the removees are removed as in Case 1.
```suggestion
Otherwise, the removees are removed as in Case 1 and the invitation is accepted for all users of the invitation.
```

2021-07-02 06:39 UTC, franziskuskiefer requested changes
I have comments [here](https://docs.google.com/document/d/1DA2aaHN1regCUXVrVADQ-n4bujX3k4FTzdmFS8mtJwg/edit#heading=h.2ddlowkh59ux)

2023-05-10 08:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-server?pullRequest=1627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-server?pullRequest=1627) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-server?pullRequest=1627) it.</sub>

2023-05-11 10:01 UTC, closed without merging