add first mapping
wireapp/wire-server pull request #1869
Opened 2021-10-19 15:23 UTC by julialongtin

https://wearezeta.atlassian.net/browse/SQPIT-737

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] **changelog.d** contains the following bits of information:
   - [x] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

2021-12-02 17:11 UTC, mythsunwind commented
Before merging this into `develop` can someone please merge the PR https://github.com/wireapp/wire-server/pull/1960 into this one. The PR includes the subsystem mapping (@S1, @S2...) and was based on the `test_mappings` branch.

2021-12-13 14:26 UTC, fisx requested changes

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Auth.hs
> +-- | Test that trying to log in with a wrong password or non-existent email fails.
```suggestion
-- The testLoginFailure test conforms to the following testing standards:
-- @SF.Provisioning @TSFI.RESTfulAPI @S2
--
-- Test that trying to log in with a wrong password or non-existent email fails.
```

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Auth.hs
> +
```suggestion
```

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Auth.hs
> +-- | Test that invalid and expired tokens do not work.
```suggestion
-- The testInvalidCookie test conforms to the following testing standards:
-- @SF.Provisioning @TSFI.RESTfulAPI @S2
--
-- Test that invalid and expired tokens do not work.
```

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Auth.hs
> +
```suggestion
```

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Client.hs
> +
```suggestion
```

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Client.hs
> +
```suggestion
```

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Client.hs
> +
```suggestion
```

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Client.hs
> +
```suggestion
```

2021-12-13 14:26 UTC, fisx commented on services/brig/test/integration/API/User/Handles.hs
> +-- | Test changes to the user's handle.
```suggestion
-- The next line contains a mapping from the testHandleUpdate test to the following test standards:
-- @SF.Provisioning @TSFI.RESTfulAPI @S2
--
-- Test changes to the user's handle.
```

2021-12-13 14:26 UTC, fisx commented on services/spar/test-integration/Test/Spar/Scim/AuthSpec.hs
>  -- | Test that a token can only be created as a team owner
```suggestion
-- @SF.Provisioning @TSFI.RESTfulAPI @S2
-- Test that a token can only be created as a team owner
```

2021-12-13 14:26 UTC, fisx commented on services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
>  -- | Test that user creation fails if handle is invalid
```suggestion
--
-- Test that user creation fails if handle is invalid
```

2021-12-13 14:36 UTC, fisx approved these changes

2021-12-14 12:27 UTC, merged