Fix: push events when AppLock or SelfDeletingMessages config change.
wireapp/wire-server pull request #1901
Opened 2021-11-01 21:21 UTC by fisx

## Checklist

 - [ ] The **PR Title** explains the impact of the change.
 - [ ] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [ ] If HTTP endpoint paths have been added or renamed, the **endpoint / config-flag checklist** (see Wire-employee only backend [wiki page](https://github.com/zinfra/backend-wiki/wiki/Checklists)) has been followed.
 - [ ] If a cassandra schema migration has been added, I ran **`make git-add-cassandra-schema`** to update the cassandra schema documentation.
 - [ ] **changelog.d** contains the following bits of information:
   - [ ] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.
   - [ ] If new config options introduced: added usage description under docs/reference/config-options.md
   - [ ] If new config options introduced: recommended measures to be taken by on-premise instance operators.
   - [ ] If a cassandra schema migration is backwards incompatible (see also [these docs](https://github.com/wireapp/wire-server/blob/develop/docs/developer/cassandra-interaction.md#cassandra-schema-migrations)), measures to be taken by on-premise instance operators are explained.
   - [ ] If a data migration (not schema migration) introduced: measures to be taken by on-premise instance operators.
   - [ ] If public end-points have been changed or added: does nginz need un upgrade?
   - [ ] If internal end-points have been added or changed: which services have to be deployed in a specific order?

2021-11-04 09:52 UTC, battermann approved these changes
LGTM AFAICT
There is a non-exhaustive pattern match which is not really part of this PR, but anyway I think it is good to keep an eye on this.

2021-11-04 09:52 UTC, battermann commented on libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
>        TeamFeatureSelfDeletingMessages -> tag _EdFeatureSelfDeletingMessagesChanged (unnamed schema)
My linter says that the pattern match is not exhaustive and `TeamFeatureClassifiedDomains` is not matched. Not sure if this is an issue or not?

2021-11-04 10:56 UTC, battermann requested changes
Looks like there are two issues that cause the build to fail, see comments.

2021-11-04 10:56 UTC, battermann commented on libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
>        TeamFeatureSelfDeletingMessages -> tag _EdFeatureSelfDeletingMessagesChanged (unnamed schema)
This actually causes the build to fail.

2021-11-04 10:56 UTC, battermann commented on libs/wire-api/src/Wire/API/Event/FeatureConfig.hs
>    | EdFeatureApplockChanged (TeamFeatureStatusWithConfig TeamFeatureAppLockConfig)
Removing `TeamFeatureClassifiedDomainsConfig` causes build to fail due to unused imports.

2021-11-04 21:45 UTC, fisx commented
Right.  These events aren't emitted anywhere, but removing them from the code is trickier than I thought.  So let's stick with defining events for all `TeamFeatureName`s exhaustively for now, even for the ones that aren't emitted.

2021-11-05 12:21 UTC, battermann approved these changes
LGTM

2021-11-05 14:16 UTC, battermann approved these changes

2021-11-05 16:27 UTC, merged