Spar Polysemy: In-memory interpreters
wireapp/wire-server pull request #1920
Opened 2021-11-09 21:52 UTC by isovector

This PR adds several in-memory interpreters for Spar's polysemy effects.

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

2021-11-09 21:52 UTC, isovector commented on services/spar/src/Spar/Sem/SAMLUserStore/Mem.hs
> +    -- TODO(sandy): Is it OK to ignore uid here?
@fisx is it? :)

2021-11-10 12:24 UTC, fisx requested changes

2021-11-10 12:24 UTC, fisx commented on services/spar/src/Spar/Sem/ScimTokenStore/Mem.hs
> +    GetByTeam tid -> gets $ filter ((== tid) . stiTeam) . M.elems
```suggestion
    LookupByTeam tid -> gets $ filter ((== tid) . stiTeam) . M.elems
```

2021-11-10 12:24 UTC, fisx commented on services/spar/src/Spar/Sem/AReqIDStore/Mem.hs
> +          Nothing -> pure Nothing
this is a different effect.  see [here](https://github.com/wireapp/wire-server/blob/922ec36f798459adc2a7f11fbeb19f2ccbd264fb/services/spar/src/Spar/Data.hs#L185) vs. [here](https://github.com/wireapp/wire-server/blob/922ec36f798459adc2a7f11fbeb19f2ccbd264fb/services/spar/src/Spar/Data.hs#L255)

2021-11-22 01:44 UTC, isovector commented on services/spar/src/Spar/Sem/ScimTokenStore/Mem.hs
> +    GetByTeam tid -> gets $ filter ((== tid) . stiTeam) . M.elems
Different PR ok?

2021-11-22 01:45 UTC, isovector commented
@fisx PTAL

2021-11-24 22:29 UTC, fisx approved these changes

2021-11-24 22:56 UTC, merged