SQSERVICES-1160 New internal endpoint to configure the guest links team feature
wireapp/wire-server pull request #1993
Opened 2021-12-14 14:48 UTC by battermann

https://wearezeta.atlassian.net/browse/SQSERVICES-1169

## Checklist

 - [ ] The **PR Title** explains the impact of the change.
 - [ ] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [ ] If HTTP endpoint paths have been added or renamed, the **endpoint / config-flag checklist** (see Wire-employee only backend [wiki page](https://github.com/zinfra/backend-wiki/wiki/Checklists)) has been followed.
 - [ ] If a cassandra schema migration has been added, I ran **`make git-add-cassandra-schema`** to update the cassandra schema documentation.
 - [ ] **changelog.d** contains the following bits of information ([details](https://github.com/wireapp/wire-server/blob/develop/docs/developer/changelog.md)):
   - [ ] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.
   - [ ] If new config options introduced: added usage description under docs/reference/config-options.md
   - [ ] If new config options introduced: recommended measures to be taken by on-premise instance operators.
   - [ ] If a cassandra schema migration is backwards incompatible (see also [these docs](https://github.com/wireapp/wire-server/blob/develop/docs/developer/cassandra-interaction.md#cassandra-schema-migrations)), measures to be taken by on-premise instance operators are explained.
   - [ ] If a data migration (not schema migration) introduced: measures to be taken by on-premise instance operators.
   - [ ] If public end-points have been changed or added: does nginz need un upgrade?
   - [ ] If internal end-points have been added or changed: which services have to be deployed in a specific order?

2021-12-15 10:05 UTC, fisx approved these changes

2021-12-15 10:05 UTC, fisx commented on services/galley/src/Galley/API/Teams/Features.hs
> +      Nothing -> cfgDefault
I think this is a genuine fix, but it's still not completely correct.  Shouldn't the lock status in L647 come from cassandra, not the default?

(Wow, this is complicated, though.  Why is this so complicated?)

2021-12-15 10:05 UTC, fisx commented on services/galley/src/Galley/API/Teams/Features.hs
> +      Nothing -> cfgDefault
(And have we been making the same mistake elsewhere?)

2021-12-17 12:49 UTC, fisx requested changes
close!  :)

2021-12-17 12:49 UTC, fisx commented on services/galley/schema/src/Main.hs
>        -- 'schemaVersion' in Galley.Cassandra
```
       -- When adding migrations here, don't forget to update
       -- 'schemaVersion' in Galley.Cassandra
```

2021-12-17 12:49 UTC, fisx commented on services/galley/schema/src/V57_GuestLinksLockStatus.hs
> +          guest_links_lock_status int
should this be consistent with the symbol?

```
type KnownTeamFeatureNameSymbol 'TeamFeatureGuestLinks = "conversationGuestLinks"
```

2021-12-17 12:49 UTC, fisx commented on services/galley/src/Galley/API/Teams/Features.hs
> +      (Public.Locked, _) -> cfgDefault {Public.tfwoapsLockStatus = lockStatus}
[nit-pick] not sure i like this change.  it's less direct.  (then again it's more resilient to change in the pattern, possibly.)

2021-12-17 13:07 UTC, battermann commented on services/galley/schema/src/Main.hs
>        -- 'schemaVersion' in Galley.Cassandra
done

2021-12-17 13:17 UTC, fisx approved these changes

2021-12-17 16:24 UTC, merged