stop deleting clients when no prekeys exist for these clients
wireapp/wire-server pull request #2689
Opened 2022-09-14 15:11 UTC by stefanwire

https://wearezeta.atlassian.net/browse/FS-950

## Checklist

 - [ ] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

2022-09-14 17:41 UTC, jschaul reviewed
I'm not convinced the approach of pushing code to production then looking at logs is fruitful in the backend's case; the feedback loop is too long and the risk of damage done of leaving *more* state inconsistency for more users is high. If this state can be achieved with current code, then it's possible to write an integration test showing clients without prekeys existing either in brig, or galley, or both. Then the production code could be changed.

The above is my gut feeling; I've not been involved with this issue before and don't have prior context; but it sounds like a bug regarding clients was introduced accidentally at some point in the recent past; Perhaps a review of code changes here would be more fruitful.

2022-09-15 08:55 UTC, elland commented on services/brig/src/Brig/API/Client.hs
> +  -- Intra.rmClient u c
I assume at some point we need to actually delete the clients correctly everywhere or is that not the case? Also would that require some script to prune the required Casandras?

2022-09-15 08:57 UTC, stefanwire commented
The discussion continues in https://wearezeta.atlassian.net/browse/FS-966.

2022-09-15 15:19 UTC, jschaul requested changes
"requesting changes" here to block this PR from being merged until the discussion in FS-966 has lead to a consensus.

2022-10-13 09:00 UTC, smatting commented
Closing this. See details in https://wearezeta.atlassian.net/browse/FS-966

2022-10-13 09:00 UTC, closed without merging