JCT-147: update SCIM documentation how to deactivate user
wireapp/wire-server pull request #2720
Opened 2022-09-22 09:57 UTC by Veki301

## Checklist

 - [ ] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [ ] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

2022-09-23 15:49 UTC, fisx approved these changes
Thanks!  Could you also add a changelog file under `changelog.d/4-docs/pr-2720` that contains just the string "Document user deactivation (aka suspension) with SCIM."?

I would do it myself, but it's your fork.  :)

2022-09-23 15:49 UTC, fisx commented on docs/src/understand/single-sign-on/main.rst
> +It is possible to temporarily deactivate an user (and reactivate him later) by setting his ``active`` property to ``true/false`` without affecting his device history.
```suggestion
It is possible to temporarily deactivate an user (and reactivate him later) by setting his ``active`` property to ``true/false`` without affecting his device history.  (`active=false` changes the wire user status to `suspended`.)
```

2022-09-26 09:14 UTC, fisx requested changes
see above comments.

2022-09-26 09:24 UTC, Veki301 commented
@fisx added changelog, please merge once checks are done, thank you :)

2022-09-26 09:41 UTC, fisx approved these changes

2022-09-26 09:41 UTC, merged