adding note about deeplinks
wireapp/wire-server pull request #2826
Opened 2022-11-07 12:21 UTC by arthurwolf

## Checklist

 - [ ] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [ ] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

2022-11-07 12:29 UTC, arthurwolf commented
![Uploading Screenshot from 2022-11-07 13-28-54.png…]()

2022-11-07 12:51 UTC, paulwire requested changes
I dont think the part "non-web Wire app (desktop, mobile)" is correct, I dont think a desktop app knows what to do with a deeplink. To my knowledge they only work with mobile apps (Android, iOS)

2022-11-07 12:59 UTC, paulwire approved these changes

2022-11-15 11:36 UTC, paul-learning approved these changes

2022-11-15 11:36 UTC, paul-learning approved these changes

2022-11-15 11:37 UTC, paulwire approved these changes

2022-11-15 11:40 UTC, merged