Removed Global Team Conversation.
wireapp/wire-server pull request #2906
Opened 2022-12-07 13:28 UTC by elland

With this we can have a clean slate on `develop` to start the long lived `mls` branch.

2022-12-08 13:39 UTC, smatting requested changes

2022-12-08 13:39 UTC, smatting commented on services/galley/src/Galley/Cassandra/Instances.hs
> -    4 -> pure GlobalTeamConv
I think we need to keep this. There are currently already values in the DB with "4". If we don't keep this then processes will crash upon reading

2022-12-08 15:51 UTC, mdimjasevic commented
Could this PR have started off by introducing revert commits of earlier GTC PRs and then making changes on top? That would have made reviewing much easier.

2022-12-09 14:40 UTC, smatting commented
Closing this in favor of https://github.com/wireapp/wire-server/pull/2916
which is just reverts with this outcome
```
> 46 files changed, 265 insertions(+), 1033 deletions(-)
```
Compare to the changes from this branch
```
19 files changed, 47 insertions(+), 592 deletions(-)
```

2022-12-09 14:40 UTC, closed without merging