Add /self/supported-protocols to nginz routes
wireapp/wire-server pull request #3358
Opened 2023-06-15 15:29 UTC by pcapriotti

## Checklist

 - [x] No CHANGELOG entry
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

2023-06-15 15:32 UTC, smatting approved these changes

2023-06-15 15:41 UTC, smatting requested changes
Target branch should be `mls`, I think

2023-06-16 07:43 UTC, pcapriotti commented
> Target branch should be `mls`, I think

Why? Supported protocols have been merged to develop (https://github.com/wireapp/wire-server/pull/3326).

2023-06-16 12:04 UTC, smatting approved these changes
Ah, I assumed that was only on the `mls` branch

2023-06-16 12:04 UTC, merged