Fix MLS message notification bug
wireapp/wire-server pull request #3610
Opened 2023-09-25 14:07 UTC by pcapriotti

This PR fixes a bug where some clients do not see MLS message notifications when fetching them with a `client` query parameter. The problem is that MLS message notifications are sent to gundeck as a single push, which will in general contain different `Recipient` objects for different clients of the same users. This makes the entries conflict with one another in cassandra, and therefore only one client ends up being stored in the database.

The fix here is "condensing" consecutive `Recipient` items relating to the same user by joining them together into a single `Recipient` object. This works because because recipient lists are generated by user.

## Checklist

 - [ ] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [ ] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

2023-09-29 09:06 UTC, smatting requested changes

2023-09-29 09:06 UTC, smatting commented on services/galley/src/Galley/API/Federation.hs
> +
Leftofter

2023-10-11 12:44 UTC, pcapriotti commented on services/galley/src/Galley/API/Federation.hs
> +
Fixed, thanks

2023-10-13 11:21 UTC, mdimjasevic approved these changes

2023-10-13 13:14 UTC, merged